weights: weights/yolov5m.pt
cfg: models/yolov5m.yaml
data: data/DOTA_ROTATED.yaml
hyp: data/hyps/hyp.finetune.windows.yaml
epochs: 20
batch_size: 1
imgsz: 416
device: '0'
rect: false
resume: false
nosave: false
noval: false
noautoanchor: true
evolve: null
bucket: ''
cache: null
image_weights: false
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 4
project: runs/train
entity: null
name: exp_models/yolov5m.yaml
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
patience: 100
begin_val: 10
end_mosaic: 0
divisor: 2
save_dir: runs\train\exp_models\yolov5m15.yaml
